USE [master]
GO
/****** Object:  Database [UCEMA]    Script Date: 25/3/2023 00:13:45 ******/
CREATE DATABASE [UCEMA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UCEMA', FILENAME = N'C:\Documents\AP6\Database\UCEMA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UCEMA_log', FILENAME = N'C:\Documents\AP6\Database\UCEMA_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [UCEMA] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UCEMA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UCEMA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UCEMA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UCEMA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UCEMA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UCEMA] SET ARITHABORT OFF 
GO
ALTER DATABASE [UCEMA] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [UCEMA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UCEMA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UCEMA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UCEMA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UCEMA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UCEMA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UCEMA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UCEMA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UCEMA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UCEMA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UCEMA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UCEMA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UCEMA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UCEMA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UCEMA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UCEMA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UCEMA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [UCEMA] SET  MULTI_USER 
GO
ALTER DATABASE [UCEMA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UCEMA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UCEMA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UCEMA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [UCEMA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [UCEMA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [UCEMA] SET QUERY_STORE = OFF
GO
USE [UCEMA]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 25/3/2023 00:13:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[ClienteId] [int] NOT NULL,
	[Nombre] [nvarchar](25) NOT NULL,
	[FechaAlta] [date] NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[ClienteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Telefono]    Script Date: 25/3/2023 00:13:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Telefono](
	[TelefonoId] [int] NOT NULL,
	[ClienteId] [int] NOT NULL,
	[Numero] [nvarchar](15) NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_Telefono] PRIMARY KEY CLUSTERED 
(
	[TelefonoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (1, N'Irene Menéndez', CAST(N'2017-12-23' AS Date), 0)
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (2, N'Pablo Sandoval', CAST(N'1943-06-26' AS Date), 1)
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (3, N'Liliana Coloto', CAST(N'2015-06-22' AS Date), 0)
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (4, N'Isidoro Gómez', CAST(N'2011-03-10' AS Date), 1)
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (5, N'Ricardo Morales', CAST(N'2016-01-10' AS Date), 0)
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (6, N'Amelia Gutierrez', CAST(N'2010-12-28' AS Date), 1)
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (7, N'Alfredo Mamaní', CAST(N'2011-11-24' AS Date), 1)
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (8, N'Augusto Scheurer', CAST(N'2013-11-20' AS Date), 0)
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (9, N'Benjamín Espósito', CAST(N'2023-03-06' AS Date), 1)
GO
INSERT [dbo].[Telefono] ([TelefonoId], [ClienteId], [Numero], [Activo]) VALUES (1, 3, N'783-747-1398', 1)
GO
INSERT [dbo].[Telefono] ([TelefonoId], [ClienteId], [Numero], [Activo]) VALUES (2, 6, N'515-962-4716', 0)
GO
INSERT [dbo].[Telefono] ([TelefonoId], [ClienteId], [Numero], [Activo]) VALUES (3, 2, N'202-659-1984', 1)
GO
INSERT [dbo].[Telefono] ([TelefonoId], [ClienteId], [Numero], [Activo]) VALUES (4, 2, N'814-260-7380', 1)
GO
INSERT [dbo].[Telefono] ([TelefonoId], [ClienteId], [Numero], [Activo]) VALUES (5, 6, N'422-494-2380', 0)
GO
INSERT [dbo].[Telefono] ([TelefonoId], [ClienteId], [Numero], [Activo]) VALUES (6, 2, N'629-412-1577', 1)
GO
ALTER TABLE [dbo].[Telefono]  WITH CHECK ADD  CONSTRAINT [FK_Telefono_Cliente] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Cliente] ([ClienteId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Telefono] CHECK CONSTRAINT [FK_Telefono_Cliente]
GO
USE [master]
GO
ALTER DATABASE [UCEMA] SET  READ_WRITE 
GO
